package contracts

import org.springframework.cloud.contract.spec.Contract

Contract.make {
    description("should return a building indicators")
    request {
        method POST()
        url("/indicators/buildings")
        headers {
            contentType('application/json')
        }
        body '''
		        {
			          "organizationCode": "UNOFI",
			          "requestedDate": "2022-01-31",
			          "holderTypeCodes": ["BUILDING", "RENTED_UNIT", "PARKING"],
			          "assetCode": "59L1",
			          "parentCode": "59L",
			          "allAssets": false,
			          "authorizedAssetCodes": ["59L","59L1"]
		        }
		    '''

    }
    response {
        body'''
           {
             "code":"",
             "name":"",
             "type":"",
             "parentCode":"",
             "parentName":"",
             "address":"",
             "lat":null,
             "lng":null,
             "photo":null,
             "photoId":null,
             "model3DUrn":null,
             "model3DDocumentation":null,
             "coreBusiness":"",
             "documentationLink":null,
             "effectiveDate":"1000-01-01",
             "expirationDate":"3000-01-01",
             "sold":true,
             "generalIndicator":{
                 "rentalArea":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 },
                 "aboveGroundLevelNumber":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 },
                 "belowGroundLevelNumber":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 },
                 "numberOfParking":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 },
                 "buildingClass":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 },
                 "area":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 },
                 "efficiencyArea":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 }
             },
             "exploitationIndicator":{
                 "buildingDate":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 },
                 "globalBuildingRating":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 },
                 "lastWorkAcceptanceDate":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 },
                 "annualExploitationRatio":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 },
                 "annualTechnicalMaintenanceRatio":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 },
                 "annualInvestment":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 }
             },
             "occupancyIndicator":{
                 "leaseCount":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 },
                 "nextLeaseDeadline":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 },
                 "leaseOccupancyRatio":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 },
                 "numberOfParkingByNatureTable":{
                     "tableValues":[]
                 },
                 "leaseRentedAreasTable":{
                     "tableValues":[],
                     "footer":{
                         "totalArea":{
                             "value":null,
                             "type":"COUNT",
                             "year":null
                         },
                         "totalRent":{
                             "value":null,
                             "type":"COUNT",
                             "year":null
                         },
                         "totalRentByRentedArea":{
                             "value":null,
                             "type":"COUNT",
                             "year":null
                         }
                     }
                 },
                 "rentalContractTable":{
                     "tableValues":[],
                     "footer":{
                         "totalRent":{
                             "value":null,
                             "type":"COUNT",
                             "year":null
                         }
                     }
                 },
                 "vacancyRentalAreasTable":{
                     "tableValues":[]
                 },
                 "rentedAreasGroupedByDate":{
                     "tableValues":[],
                     "footer":{
                         "totalArea":{
                             "value":null,
                             "type":"COUNT",
                             "year":null
                         },
                         "totalRent":{
                             "value":null,
                             "type":"COUNT",
                             "year":null
                         },
                         "totalRentByRentedArea":{
                             "value":null,
                             "type":"COUNT",
                             "year":null
                         }
                     }
                 },
                 "areaByCoreBusiness":{
                     "value":null,
                     "type":"COUNT",
                     "year":null,
                     "graphValues":[]
                 }
             },
             "environmentIndicator":{
                 "annualCarbonEquivalence":{
                     "value":null,
                     "type":"COUNT",
                     "year":null,
                     "graphValues":[]
                 },
                 "annualEnergyConsumptionByArea":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 },
                 "energyPerformance":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 },
                 "greenHouseGas":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 },
                 "certificates":[]
             },
             "financialIndicator":{
                 "annualOpex":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 },
                 "annualCapex":{
                     "value":null,
                     "type":"COUNT",
                     "year":null
                 }
             },
             "buildingStatus":"ACTIVE",
             "arbitrage":{
                 "type":"NO",
                 "effectiveDate":null
             }
           }
        '''
        status 200
    }
}
